### ISSUE TITLE
can not deploy CROssBAR web

### ISSUE THREAD

**Issue by aixi** [cansyl/CROssBAR#2]
I'm trying to deploy CROssBAR web by using nginx and php-fpm. After I deploy, I find the web service need a mysql database in database.php, can you tell me the table schema of the database. Thanks.
![image](https://user-images.githubusercontent.com/9337523/204241077-df385b27-bef5-4b67-bcf3-06d489e5f6a0.png)

**Comment by atakanahmetce** [comment]
Thank you for your interest in CROssBAR Web-Service. Database schema (structure only) is provided under the [CROssBAR Web-service folder](https://github.com/cansyl/CROssBAR/tree/master/CROssBAR_Web-service). Please keep in mind that you also need to modify line 8 at the "database.php" file according to your server and database name.

**Comment by aixi** [comment]
thanks
